dist: Bionic

language: python

sudo: required

python:
  - "3.7"

services:
  - mysql

env:
  global:
    - DJANGO_MYSQL_HOST="127.0.0.1"
    - DJANGO_MYSQL_USER="travis"
    - DJANGO_SETTINGS_MODULE="travis_ci.settings"

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install python-dev python3-dev libmysqlclient-dev -y
  - sudo cp $TRAVIS_BUILD_DIR/travis_ci/mysql.cnf /etc/mysql/conf.d/
  - sudo service mysql restart

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE `madswan` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;'
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py check
